const safeGet = key => { try { return localStorage.getItem(key) } catch { return null } }
const safeSet = (key, value) => { try { localStorage.setItem(key, value) } catch {} }
const $ = s => document.querySelector(s)
const skills = [
  ['listening','A radio interview about urban gardening in Melbourne.','#3B82F6'],
  ['speaking','Share your view in a lively city conversation.','#F59E0B'],
  ['reading','Explore a feature on a changing urban landscape.','#10B981'],
  ['writing','Write a clear response with a view of the city.','#8B5CF6']
]
const sceneImages = {
  listening:'https://images.unsplash.com/photo-1511081692775-05d0f180a065?auto=format&fit=crop&w=1200&q=85',
  speaking:'https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=1200&q=85',
  reading:'https://images.unsplash.com/photo-1507842217343-583bb7270b66?auto=format&fit=crop&w=1200&q=85',
  writing:'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1200&q=85'
}
const fallback = {morning:'linear-gradient(135deg,#FEF3C7,#FDE68A)',afternoon:'linear-gradient(135deg,#DBEAFE,#93C5FD)',evening:'linear-gradient(135deg,#F3E8FF,#E879F9 50%,#FB923C)',night:'linear-gradient(135deg,#1E1B4B,#312E81 50%,#0F172A)'}
const hour = new Date().getHours(); const time = hour >= 6 && hour < 12 ? 'morning' : hour < 17 ? 'afternoon' : hour < 21 ? 'evening' : 'night'
const city = $('#city'); const poster=document.createElement('img');poster.className='village-poster';poster.src='public/images/gomapped-village-morning.png';poster.alt='GoMappED village practice map';city.append(poster);const village = document.createElement('video'); village.className='village-image';village.src='public/video/gomapped-village-morning.mp4';village.autoplay=true;village.loop=true;village.muted=true;village.playsInline=true;village.preload='auto';village.addEventListener('playing',()=>poster.classList.add('hidden'));village.onerror=()=>{city.style.background=fallback[time];village.remove()};city.append(village);village.play().catch(()=>{/* file-preview restriction: retain the poster */})
const today = new Date(); $('#today-label').textContent = new Intl.DateTimeFormat('en-GB',{weekday:'short',day:'numeric',month:'short',year:'numeric'}).format(today)
function dateValue(d){return d.toISOString().slice(0,10)}
const target = safeGet('targetScore') || '6.5'; const exam = safeGet('examDate');
function updateTarget(){ if(!exam){$('#target-label').textContent=`Target: ${target}`;return} const days=Math.ceil((new Date(exam)-new Date(today.toDateString()))/86400000);$('#target-label').textContent=`Target: ${safeGet('targetScore') || target} · ${days < 0 ? 'Exam day!' : `${days} days left`}` } updateTarget()
function buildCalendar(){const calendar=$('#calendar'); for(let offset=-6;offset<=7;offset++){const d=new Date(today);d.setDate(today.getDate()+offset);const isToday=offset===0;const isExam=exam===dateValue(d);const el=document.createElement('span');el.className=`day ${isToday?'current':offset<0?(offset===-1?'past':'missed'):'future'} ${isExam?'exam':''}`;el.textContent=isExam?'🏁':offset<0?'✕':d.getDate();el.title=dateValue(d);calendar.append(el)}} buildCalendar()
const sceneArea=$('#scenes'); skills.forEach(([skill,description,colour],i)=>{const score = null;const el=document.createElement('article');el.className=`scene ${skill}`;el.style.setProperty('--skill-colour',colour);el.tabIndex=0;el.setAttribute('role','link');el.setAttribute('aria-label',`${skill} practice: ${description}`);el.innerHTML=`<span class="hotspot-marker"><i></i><span class="hotspot-copy"><b>${skill.toUpperCase()}</b><small>${description}</small><em>${score!==null?`Score: ${score}`:'Start practice →'}</em></span></span>`;const launch=()=>{if(!el.classList.contains('revealed')){el.classList.add('revealed');return}$('#arrival').classList.add('hide');const route=location.protocol==='file:'?'weclass/ai/trial/index.html':'/weclass/ai/trial';window.location.href=`${route}?skill=${skill}&sessionId=demo-${skill}`};el.onclick=launch;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' ')launch()};sceneArea.append(el)})
const scores={listening:5.0,speaking:5.5,reading:4.5,writing:5.0};const overall=5.0;const petalPaths=['M60 60 Q45 40 60 15 Q75 40 60 60Z','M60 60 Q80 45 105 60 Q80 75 60 60Z','M60 60 Q45 80 60 105 Q75 80 60 60Z','M60 60 Q40 45 15 60 Q40 75 60 60Z'];const petalSkills=['listening','speaking','reading','writing'];$('#petals').innerHTML=petalPaths.map((path,i)=>{const progress=Math.min(scores[petalSkills[i]]/parseFloat(target),1);return `<path d="${path}" fill="${skills[i][2]}" opacity=".9" transform="translate(60 60) scale(${progress}) translate(-60 -60)"/>`}).join('');$('#overall-score').textContent=overall;$('#target-score').textContent=`→ ${target}`
const flower=$('#flower'),panel=$('#flower-panel'); flower.onclick=e=>{e.stopPropagation();panel.hidden=!panel.hidden;if(!panel.hidden)panel.innerHTML=`<h3>Overall&nbsp;&nbsp; ${overall} → ${target}</h3>${petalSkills.map((s,i)=>`<p><span><i class="dot" style="background:${skills[i][2]}"></i>${s[0].toUpperCase()+s.slice(1)}</span><span>${scores[s]} <b class="up">↑</b></span></p>`).join('')}`};document.addEventListener('click',e=>{if(!panel.hidden&&!panel.contains(e.target))panel.hidden=true})
if(!safeGet('targetScore')&&!safeGet('examDate')){setTimeout(()=>$('#modal-wrap').hidden=false,3000);let selected;['5.5','6.0','6.5','7.0','7.5+'].forEach(value=>{const b=document.createElement('button');b.textContent=value;b.onclick=()=>{selected=value;[...$('#score-options').children].forEach(x=>x.classList.remove('selected'));b.classList.add('selected');$('#date-step').hidden=false};$('#score-options').append(b)});$('#exam-date').min=dateValue(today);$('#start-button').onclick=()=>{const date=$('#exam-date').value;if(!selected||!date)return;safeSet('targetScore',selected);safeSet('examDate',date);$('#modal-wrap').hidden=true;updateTarget()}}
if(safeGet('userId')){$('#return-hook').hidden=false;safeSet('lastVisit',today.toDateString())}window.addEventListener('sessionComplete',()=>{if(!safeGet('userId')){flower.classList.add('pulse');setTimeout(()=>$('#login-hook').hidden=false,600)}})
